spring:
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASSWORD:guest}
  application:
    name: example
  datasource:
    username: ${DATABASE_USER:postgres}
    password: ${DATABASE_PASSWORD:postgres}
    url: ${DATABASE_HOST_JDBC:jdbc:postgresql://localhost:5432}/comment-service
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:/db/master.xml
  jpa:
    hibernate:
      ddl-auto: update
  mvc:
    async:
      request-timeout: -1
server:
  port: ${SERVER_HTTP_PORT:8083}
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs