apiVersion: v1
kind: Service
metadata:
  name: comment-service
spec:
  selector:
    app: comment-service-application
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: comment-service-application
  labels:
    app: comment-service-application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: comment-service-application
  template:
    metadata:
      labels:
        app: comment-service-application
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
    spec:
      containers:
        - name: comment-service
          image: ghcr.io/hackathon-x-mode/comment-service:main
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
          envFrom:
            - configMapRef:
                name: common-service-envs
      imagePullSecrets:
        - name: regcred